version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Path to the backend Dockerfile (in the root)
    ports:
      - "3001:3000"  # Host port 3001, container port 3000 (backend)
    networks:
      - ecommerce-network

  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile  # Path to the frontend Dockerfile (in the public folder)
    ports:
      - "3000:80"  # Host port 3000, container port 80 (frontend)
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
